on:
  push:
    branches:
      - development
name: 🚀 Deploy development on push
jobs:
  web-deploy:
    name: 🎉 Deploy-develop-serv
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.sadigit.co.id
        username: ${{ secrets.FTP_USERNAME_DEVEL }}
        password: ${{ secrets.FTP_PASSWORD_DEVEL }}
